name: code_store_card_scanner_android
description: Android implementation of code_store_card_scanner using native Google Play Services ML Kit.
version: 1.0.0
publish_to: 'none'
repository: https://github.com/vishnu32510/code_store/tree/main/packages/code_store_card_scanner_android
issue_tracker: https://github.com/vishnu32510/code_store/issues
topics:
  - card-scanner
  - credit-card
  - mlkit
  - ocr
  - play-services

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: native_card_scanner
    platforms:
      android:
        package: com.nungu.codestore.card_scanner_android
        pluginClass: CardScannerAndroidPlugin

dependencies:
  flutter:
    sdk: flutter
  code_store_card_scanner_platform_interface:
    path: ../code_store_card_scanner_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
