name: code_store_dynamic_island
description: "Modular Dynamic Island engine for iOS Live Activities with sprite animation looping and simple status display."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.13.1 <4.0.0'
  flutter: '>=3.47.1'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^9.2.1
  meta: ^1.19.0
  image: ^4.5.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
