// Scaffold generated by home_widget. Adjust the widget for your needs.
//
// Placeholder SwiftUI widget.
//
// App Group ID used here: group.com.nungu.codestore

import SwiftUI
import WidgetKit

struct Provider: TimelineProvider {
  func placeholder(in context: Context) -> WeatherForecastWidgetHomeWidgetEntry {
    WeatherForecastWidgetHomeWidgetEntry(date: Date())
  }

  func getSnapshot(in context: Context, completion: @escaping (WeatherForecastWidgetHomeWidgetEntry) -> Void) {
    // Example of accessing data written by home_widget in Flutter:
    // let prefs = UserDefaults(suiteName: "group.com.nungu.codestore")
    // let counter = prefs?.integer(forKey: "counter") ?? 0
    completion(WeatherForecastWidgetHomeWidgetEntry(date: Date()))

  }

  func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> Void) {
    completion(Timeline(entries: [WeatherForecastWidgetHomeWidgetEntry(date: Date())], policy: .atEnd))

  }
}

struct WeatherForecastWidgetHomeWidgetEntry: TimelineEntry {
  let date: Date
}


struct WeatherForecastWidgetHomeWidgetEntryView: View {
  var entry: Provider.Entry
  var body: some View {
    VStack(spacing: 6) {
      Text("Weather Forecast")
        .font(.headline)
      
      // Displays formatted time (e.g. 7:45 PM)
      Text(entry.date, style: .time)
        .font(.subheadline)
      
      // Or displays formatted date (e.g. August 27, 2026)
      Text(entry.date, style: .date)
        .font(.caption)
        .foregroundColor(.secondary)
    }
    .applyContainerBackground()
  }
}

struct WeatherForecastWidgetHomeWidget: Widget {
  let kind: String = "WeatherForecastWidgetHomeWidget"

  var body: some WidgetConfiguration {
    StaticConfiguration(kind: kind, provider: Provider()) { entry in
      WeatherForecastWidgetHomeWidgetEntryView(entry: entry)
    }
    .configurationDisplayName("WeatherForecastWidgetHomeWidget")
  }
}

extension View {
  @ViewBuilder
  func applyContainerBackground() -> some View {
    if #available(iOSApplicationExtension 17.0, *) {
      self.containerBackground(.fill.tertiary, for: .widget)
    } else if #available(iOSApplicationExtension 15.0, *) {
      self.background()
    } else {
      self
    }
  }
}

#Preview {
    WeatherForecastWidgetHomeWidgetEntryView(
        entry: WeatherForecastWidgetHomeWidgetEntry(date: Date())
    )
}
