// Scaffold generated by home_widget. Adjust the widget for your needs.

import WidgetKit
import SwiftUI

@main
struct AppStatusWidgetHomeWidgetBundle: WidgetBundle {
  var body: some Widget {
    AppStatusWidgetHomeWidget()
  }
}
