name: code_store_card_scanner
description: Modular debit and credit card OCR scanning, real-time regex brand detection, and interactive 3D card preview for Flutter.
version: 1.0.0
repository: https://github.com/vishnu32510/code_store/tree/main/packages/code_store_card_scanner
issue_tracker: https://github.com/vishnu32510/code_store/issues
topics:
  - card-scanner
  - credit-card
  - ocr
  - payment
  - camera

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

flutter:
  uses-material-design: true
  plugin:
    platforms:
      ios:
        default_package: code_store_card_scanner_ios
      android:
        default_package: code_store_card_scanner_android

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.1
  get_it: ^9.2.1
  meta: ^1.18.0
  code_store_card_scanner_platform_interface:
    path: ../code_store_card_scanner_platform_interface
  code_store_card_scanner_ios:
    path: ../code_store_card_scanner_ios
  code_store_card_scanner_android:
    path: ../code_store_card_scanner_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
