// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApoglQ5upsRszr5bp7Gug4ZwGAjW-emMU',
    appId: '1:377191190351:web:171f7d5c4bed7c74a1bf3a',
    messagingSenderId: '377191190351',
    projectId: 'code-store001',
    authDomain: 'code-store001.firebaseapp.com',
    storageBucket: 'code-store001.firebasestorage.app',
    measurementId: 'G-2JSQPZHLMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWXYkHRWNMPZQFon5m-uhhglAccgAFY4',
    appId: '1:377191190351:android:233541ebd8d141b4a1bf3a',
    messagingSenderId: '377191190351',
    projectId: 'code-store001',
    storageBucket: 'code-store001.firebasestorage.app',
  );

  /// Web OAuth client ID — required as [GoogleSignIn.serverClientId] on Android.
  static const String googleWebClientId =
      '377191190351-gr9skl6dv66qisc0s52mbpcf748jol0s.apps.googleusercontent.com';

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RnwAQWGmCJIaBVqdfgrGfnu9xKXV0cc',
    appId: '1:377191190351:ios:963219e0f0467bffa1bf3a',
    messagingSenderId: '377191190351',
    projectId: 'code-store001',
    storageBucket: 'code-store001.firebasestorage.app',
    androidClientId: '377191190351-k0oltm0hsh5rqhsk0c1oqlppn8tikk98.apps.googleusercontent.com',
    iosClientId: '377191190351-obpufneq8f4v17u4uhqsrltaq1422elk.apps.googleusercontent.com',
    iosBundleId: 'com.nungu.codestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7RnwAQWGmCJIaBVqdfgrGfnu9xKXV0cc',
    appId: '1:377191190351:ios:963219e0f0467bffa1bf3a',
    messagingSenderId: '377191190351',
    projectId: 'code-store001',
    storageBucket: 'code-store001.firebasestorage.app',
    iosClientId: '377191190351-obpufneq8f4v17u4uhqsrltaq1422elk.apps.googleusercontent.com',
    iosBundleId: 'com.nungu.codestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApoglQ5upsRszr5bp7Gug4ZwGAjW-emMU',
    appId: '1:377191190351:web:1257f6fe16a26f18a1bf3a',
    messagingSenderId: '377191190351',
    projectId: 'code-store001',
    authDomain: 'code-store001.firebaseapp.com',
    storageBucket: 'code-store001.firebasestorage.app',
    measurementId: 'G-653JL8FZ3N',
  );
}
