// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGmculPXYp0E-OhNmYj0c2t1bG8DbzwVo',
    appId: '1:377191190351:web:972416f0bba1579ca1bf3a',
    messagingSenderId: '377191190351',
    projectId: 'code-store001',
    authDomain: 'code-store001.firebaseapp.com',
    storageBucket: 'code-store001.appspot.com',
    measurementId: 'G-W4B41SLERN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWXYkHRWNMPZQFon5m-uhhglAccgAFY4',
    appId: '1:377191190351:android:0582b14a5a7d26c9a1bf3a',
    messagingSenderId: '377191190351',
    projectId: 'code-store001',
    storageBucket: 'code-store001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7RnwAQWGmCJIaBVqdfgrGfnu9xKXV0cc',
    appId: '1:377191190351:ios:d63a2a638e3cfcb2a1bf3a',
    messagingSenderId: '377191190351',
    projectId: 'code-store001',
    storageBucket: 'code-store001.appspot.com',
    iosClientId: '377191190351-8qohu5cm10nceeg0cfrhie4an5iruunb.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeStore',
  );

}