// Scaffold generated by home_widget. Adjust the widget for your needs.
package com.nungu.codestore

import es.antonborri.home_widget.HomeWidgetGlanceWidgetReceiver

class AppStatusWidgetHomeWidgetReceiver : HomeWidgetGlanceWidgetReceiver<AppStatusWidgetHomeWidget>() {
  override val glanceAppWidget = AppStatusWidgetHomeWidget()
}
