// Scaffold generated by home_widget. Adjust the widget for your needs.
//
// This is a placeholder Glance (Jetpack Compose) widget.
package com.nungu.codestore

import androidx.compose.runtime.Composable
import android.content.Context
import androidx.compose.ui.graphics.Color
import androidx.glance.GlanceId
import androidx.glance.GlanceModifier
import androidx.glance.appwidget.GlanceAppWidget
import androidx.glance.appwidget.provideContent
import androidx.glance.background
import androidx.glance.currentState
import androidx.glance.layout.Box
import androidx.glance.layout.fillMaxSize
import androidx.glance.text.Text
import es.antonborri.home_widget.HomeWidgetGlanceState
import es.antonborri.home_widget.HomeWidgetGlanceStateDefinition

class WeatherForecastWidgetHomeWidget : GlanceAppWidget() {
  override val stateDefinition = HomeWidgetGlanceStateDefinition()

  override suspend fun provideGlance(context: Context, id: GlanceId) {
    provideContent { WidgetContent(context, currentState()) }
  }

  @Composable
  private fun WidgetContent(context: Context, currentState: HomeWidgetGlanceState) {
    // Example to access data from SharedPreferences:
    // Counter would be the "key" you stored via HomeWidget on Flutter
    // val prefs = currentState.preferences
    // val counter = prefs.getInt("counter", 0)
    Box(modifier = GlanceModifier.fillMaxSize().background(Color.White)) {
      Text(text = "WeatherForecastWidgetHomeWidget (placeholder)")
    }

  }
}


