// Scaffold generated by home_widget. Adjust the widget for your needs.
package com.nungu.codestore

import es.antonborri.home_widget.HomeWidgetGlanceWidgetReceiver

class WeatherForecastWidgetHomeWidgetReceiver : HomeWidgetGlanceWidgetReceiver<WeatherForecastWidgetHomeWidget>() {
  override val glanceAppWidget = WeatherForecastWidgetHomeWidget()
}
