name: code_store_messaging
description: "Modular Firebase Messaging & Push Notifications package with DI support, token management, foreground presentation, scheduling, rich media, and background handlers."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.13.1 <4.0.0'
  flutter: '>=3.47.1'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.13.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  dio: ^5.11.0
  path_provider: ^2.1.5
  get_it: ^9.2.1
  meta: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
