name: code_store_splash
description: "Pluggable native and animated splash screen package with main logo animation, optional native footer branding, and audio chime support."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.13.1 <4.0.0'
  flutter: '>=3.47.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.8
  audioplayers: ^6.8.1
  get_it: ^9.2.1
  meta: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
