name: code_store_card_scanner_ios
description: iOS implementation of the code_store_card_scanner plugin using native Apple Vision via Swift Package Manager.
version: 1.0.0
publish_to: none
repository: https://github.com/vishnu32510/code_store/tree/main/packages/code_store_card_scanner_ios
issue_tracker: https://github.com/vishnu32510/code_store/issues
topics:
  - card-scanner
  - credit-card
  - apple-vision
  - ocr
  - spm

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: native_card_scanner
    platforms:
      ios:
        dartPluginClass: CardScannerIos

dependencies:
  flutter:
    sdk: flutter
  code_store_card_scanner_platform_interface:
    path: ../code_store_card_scanner_platform_interface
  apple_vision_commons: ^0.0.3
  apple_vision_recognize_text: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
publish_to: none
