name: code_store_card_scanner_ios
description: iOS implementation of the code_store_card_scanner plugin using native Apple Vision (SPM).
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: code_store_card_scanner
    platforms:
      ios:
        dartPluginClass: CardScannerIos

dependencies:
  flutter:
    sdk: flutter
  code_store_card_scanner_platform_interface:
    path: ../code_store_card_scanner_platform_interface
  apple_vision_commons: ^0.0.3
  apple_vision_recognize_text: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
